export const formsMock = [
  {
    id: 1,
    titulo: 'Formulário de Cadastro',
    descricao: 'Formulário para cadastro de novos usuários.',
    data_inicial: '01/10/2023',
    data_final: '31/10/2023',
    respostasCount: 100,
    link: '/forms/register',
  },
  {
    id: 2,
    titulo: 'Formulário de Login',
    descricao: 'Formulário para login de usuários existentes.',
    data_inicial: '01/10/2023',
    data_final: '31/10/2023',
    respostasCount: 120,
    link: '/forms/login',
  },
  {
    id: 3,
    titulo: 'Formulário de Contato',
    descricao: 'Formulário para contato com a equipe de suporte.',
    data_inicial: '01/10/2023',
    data_final: '31/10/2023',
    respostasCount: 80,
    link: '/forms/contact',
  },
  {
    id: 4,
    titulo: 'Formulário de Desenvolvimento',
    descricao: 'Formulário para desenvolvimento de novas funcionalidades.',
    data_inicial: '01/10/2023',
    data_final: '31/10/2023',
    respostasCount: 200,
    link: '/forms/development',
  },
];